/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SISPROVA.SRBS.vista.equipo;


import com.SISPROVA.SRBS.controlador.ControladorCentro;
import com.SISPROVA.SRBS.controlador.ControladorEquipo;
import com.SISPROVA.SRBS.controlador.ControladorEstado;
import com.SISPROVA.SRBS.controlador.ControladorTipo_Documento;
import com.SISPROVA.SRBS.controlador.ControladorTipo_Usuario;
import com.SISPROVA.SRBS.vista.usuario.Agregar_Usuario;
import com.SISPROVA.SRBS.controlador.ControladorTipo_Equipo;
import com.SISPROVA.SRBS.controlador.ControladorUsuario;
import com.SISPROVA.SRBS.modelo.Equipo;
import com.SISPROVA.SRBS.modelo.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author G40-80
 */
public class Agregar_Equipo extends javax.swing.JInternalFrame {
    
    ResultSet rstipoequ;
    ResultSet rstipous;
    ResultSet rstipoestado;
    /**
     * Creates new form Agregar_Equipo
     */
    public Agregar_Equipo() {
        initComponents();
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limpiar = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        guardar_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        guardar_continuar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usuarios = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        estados = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tipos = new javax.swing.JComboBox();

        limpiar.setText("Limpiar");
        limpiar.setToolTipText("");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Equipo");

        jLabel3.setText("Nombre");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripción");
        jLabel4.setToolTipText("");

        guardar_salir.setText("Guargar y Salir");
        guardar_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_salirActionPerformed(evt);
            }
        });

        jLabel5.setText("color");

        guardar_continuar.setText("Guardar y Continuar");
        guardar_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_continuarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo Equipo");

        jLabel7.setText("Usuario");

        jLabel8.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(color, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(descripcion, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estados, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar_continuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar_salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar_continuar)
                    .addComponent(guardar_salir)
                    .addComponent(cancelar)
                    .addComponent(limpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
   Limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardar_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_salirActionPerformed
     String nom = nombre.getText().toUpperCase();
        String desc = descripcion.getText().toUpperCase();
        String col = color.getText().toUpperCase();
        int tip = tipos.getSelectedIndex()+1;
        int usuario = usuarios.getSelectedIndex()+1;
        int estado = estados.getSelectedIndex()+1;
        
       Equipo equi = new Equipo( nom, desc, col, tip, usuario, estado);
        
        ControladorEquipo control = new ControladorEquipo();
        if(control.insertarDatos(equi))JOptionPane.showMessageDialog(this, "Registro Agregado Correctamente");
        this.dispose();
    }//GEN-LAST:event_guardar_salirActionPerformed

    private void guardar_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_continuarActionPerformed
        String nom = nombre.getText().toUpperCase();
        String desc = descripcion.getText().toUpperCase();
        String col = color.getText().toUpperCase();
        int tip = tipos.getSelectedIndex()+1;
        int usuario = usuarios.getSelectedIndex()+1;
        int estado = estados.getSelectedIndex()+1;
        
       Equipo equi = new Equipo( nom, desc, col, tip, usuario, estado);
        
        ControladorEquipo eq = new ControladorEquipo();
        
        if(eq.insertarDatos(equi))JOptionPane.showMessageDialog(this, "Registro Agregado Correctamente");
        
        Limpiar();
    }//GEN-LAST:event_guardar_continuarActionPerformed
     private void llenarComboBox(){
       ControladorTipo_Equipo tipo = new ControladorTipo_Equipo();
        rstipoequ = tipo.nombre();
       ControladorUsuario usuario = new ControladorUsuario();
        rstipous = usuario.nombre();
       ControladorEstado estado = new ControladorEstado();
        rstipoestado = estado.nombre();
        
        
        try {
            while(rstipoequ.next()){
                tipos.addItem(rstipoequ.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rstipous.next()){
                usuarios.addItem(rstipous.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {              
            while(rstipoestado.next()){
                estados.addItem(rstipoestado.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Limpiar(){
        

        nombre.setText("");
        descripcion.setText("");
        color.setText("");
        tipos.setSelectedItem(0);
        usuarios.setSelectedIndex(0);
        estados.setSelectedIndex(0);
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField color;
    private javax.swing.JTextField descripcion;
    private javax.swing.JComboBox estados;
    private javax.swing.JButton guardar_continuar;
    private javax.swing.JButton guardar_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox tipos;
    private javax.swing.JComboBox usuarios;
    // End of variables declaration//GEN-END:variables
}
