/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SISPROVA.SRBS.vista.vehiculo;

import com.SISPROVA.SRBS.controlador.ControladorCentro;
import com.SISPROVA.SRBS.controlador.ControladorColor;
import com.SISPROVA.SRBS.controlador.ControladorEstado;
import com.SISPROVA.SRBS.controlador.ControladorMarca;
import com.SISPROVA.SRBS.controlador.ControladorTipo_Documento;
import com.SISPROVA.SRBS.controlador.ControladorTipo_Usuario;
import com.SISPROVA.SRBS.controlador.ControladorUsuario;
import com.SISPROVA.SRBS.controlador.ControladorVehiculo;
import com.SISPROVA.SRBS.modelo.Usuario;
import com.SISPROVA.SRBS.modelo.Vehiculo;
import com.SISPROVA.SRBS.vista.MainVista;
import com.SISPROVA.SRBS.vista.usuario.Agregar_Usuario;
import com.SISPROVA.SRBS.vista.usuario.Vista_Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Penagos
 */
public class Vista_Vehiculo extends javax.swing.JInternalFrame {

    JTable tabla;
    ResultSet rs;
    ResultSet rscolor;
    ResultSet rscentro;
    ResultSet rstipous;
    ResultSet rsestado;
    DefaultTableModel dfm;
    
    public Vista_Vehiculo() {
        initComponents();
        dfm = new DefaultTableModel();
        tabla = this.jTable1;
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cFiltroBusqueda = new javax.swing.JComboBox<String>();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MATRICULA", "MARCA", "COLOR", "NOMBRE_DUEÑO", "APELLIDO_DUEÑO", "NUM_DOCUMENTO", "TIPO_USUARIO", "ESTADO_VEHICULO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SISPROVA/SRBS/recursos/ic_add_circle_black_48dp.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SISPROVA/SRBS/recursos/ic_loop_black_48dp.png"))); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SISPROVA/SRBS/recursos/ic_create_black_48dp.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SISPROVA/SRBS/recursos/ic_clear_black_48dp.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por..");

        cFiltroBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "COLOR", "MARCA", "ESTADO", "USUARIO", "TIPO_VEHICULO" }));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SISPROVA/SRBS/recursos/ic_search_black_18dp.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(cFiltroBusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reiniciarJTable(tabla);
        buscar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reiniciarJTable(tabla);
        llenarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         DefaultTableModel tm = (DefaultTableModel) tabla.getModel();
        ControladorMarca mar = new ControladorMarca();
        ControladorTipo_Usuario tipousu = new ControladorTipo_Usuario();
        ControladorColor col = new ControladorColor();
        ControladorEstado esta = new ControladorEstado();
        ControladorUsuario usu = new ControladorUsuario();
        int id = Integer.parseInt(String.valueOf(tm.getValueAt(tabla.getSelectedRow(),0)));
        if(id != 0){
            int res = JOptionPane.showConfirmDialog(this, "Esta Seguro de Editar este Usuario");
            if(JOptionPane.YES_OPTION == res){
               String matricula = String.valueOf(tm.getValueAt(tabla.getSelectedRow(),1));
               String marca  =String.valueOf(tm.getValueAt(tabla.getSelectedRow(),2));
               int idmar= mar.idMarca(marca);
               String color =String.valueOf(tm.getValueAt(tabla.getSelectedRow(),3));
               int idcol= col.idMarca(color);
               String nombredueño =String.valueOf(tm.getValueAt(tabla.getSelectedRow(),4));
               String apellidousuario =String.valueOf(tm.getValueAt(tabla.getSelectedRow(),5));
               int idusu = usu.obtenerId2(nombredueño,apellidousuario);
               String estado =String.valueOf(tm.getValueAt(tabla.getSelectedRow(),8));
               int est = esta.retornarId(estado);
               ControladorVehiculo control = new ControladorVehiculo();
               Vehiculo veh = new Vehiculo(matricula,idmar,idcol,est,id);
               control.editar(id,veh);
               reiniciarJTable(tabla);
               llenarTabla(); 
            }       
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione una Fila");
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel tm = (DefaultTableModel) tabla.getModel();
        int id = Integer.parseInt(String.valueOf(tm.getValueAt(tabla.getSelectedRow(),0)));
        if(id != 0){
            int res = JOptionPane.showConfirmDialog(this, "Esta Seguro de Eliminar este Vehiculo");
            if(JOptionPane.YES_OPTION == res){
               ControladorVehiculo control = new ControladorVehiculo();
               control.eliminar(id);
               reiniciarJTable(tabla);
               llenarTabla(); 
            }       
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione una Fila");
        }  
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Agregar_Vehiculo agregar = new Agregar_Vehiculo();
        MainVista.escritorio.add(agregar);
        agregar.show();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void llenarTabla(){
        tabla.setModel(dfm);
         
        dfm.setColumnIdentifiers(new Object[]{"ID","MATRICULA","MARCA","COLOR","NOMBRE_DUEÑO","APELLIDO_DUEÑO","DOCUMENTO","TIPO_USUARIO","ESTADO"});
        
        ControladorVehiculo control = new ControladorVehiculo();
        rs = control.selecionarVehiculo();
        
        ControladorColor color = new ControladorColor();
        rscolor = color.nombre();
        
        ControladorEstado cestado = new ControladorEstado();
        rsestado = cestado.nombre();
        
        ControladorTipo_Usuario ctipou_suario = new ControladorTipo_Usuario();
        rstipous = ctipou_suario.nombre();
        try {
            while(rs.next()){
                dfm.addRow(new Object[]{rs.getInt("id"),rs.getString("matricula"),rs.getString("nombre"),"",rs.getString("usuario"),rs.getString("apellido"),rs.getString("numero_identidad"),"",""});
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Vista_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        TableColumn colorc = tabla.getColumnModel().getColumn(3);
        TableColumn tipous = tabla.getColumnModel().getColumn(7);
        TableColumn estado = tabla.getColumnModel().getColumn(8);
        
        JComboBox combo1 = new JComboBox();
        JComboBox combo2 = new JComboBox();
        JComboBox combo3 = new JComboBox();
   
       
        try {
            while(rstipous.next()){
              combo1.addItem(rstipous.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rscolor.next()){
              combo2.addItem(rscolor.getString("nombre_color"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rsestado.next()){
              combo3.addItem(rsestado.getString("nom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
       
        tipous.setCellEditor(new DefaultCellEditor(combo1));
        colorc.setCellEditor(new DefaultCellEditor(combo2));
        estado.setCellEditor(new DefaultCellEditor(combo3));
        combo1.setSelectedItem(0);
        combo2.setSelectedItem(0);
        combo3.setSelectedItem(0);
     
    }

      private static void reiniciarJTable(javax.swing.JTable Tabla){
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
 
        TableColumnModel modCol = Tabla.getColumnModel();
        while(modCol.getColumnCount()>0)modCol.removeColumn(modCol.getColumn(0));
    }
      
       private void buscar(){
        String campo = (String)cFiltroBusqueda.getSelectedItem();
        String src = jTextField1.getText().toUpperCase();
        
        tabla.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"ID","MATRICULA","MARCA","COLOR","NOMBRE_DUEÑO","APELLIDO_DUEÑO","DOCUMENTO","TIPO_USUARIO","ESTADO"});

        
        ControladorVehiculo control = new ControladorVehiculo();
        
        rs = control.buscarVehiculo(src, campo);
        
        try {
            while(rs.next()){
             dfm.addRow(new Object[]{rs.getInt("id"),rs.getString("matricula"),rs.getString("nombre"),"",rs.getString("usuario"),rs.getString("apellido"),rs.getString("numero_identidad"),"",""});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cFiltroBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
